### PR TITLE
feat: add go examples

### PR DESCRIPTION
**Pull request by ChocolateAceCream**
*Issue #13 , if available:*

*Description of changes:*
Add go examples

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by lovaarte** [comment]
Hi @ChocolateAceCream, thanks for PR. Your code looks to be going SigV4 instead of SigV4A. SigV4 can only handle regional signature/endpoint, however SigV4A is multi-regional. Happy to merge if you would submit SigV4A samples equivalent to how it's done in other languages in this repo.

**Comment by ChocolateAceCream** [comment]
> Hi @ChocolateAceCream, thanks for PR. Your code looks to be going SigV4 instead of SigV4A. SigV4 can only handle regional signature/endpoint, however SigV4A is multi-regional. Happy to merge if you would submit SigV4A samples equivalent to how it's done in other languages in this repo.

Hi @lovaarte, according to https://github.com/aws/aws-sdk-go-v2/issues/1935, the SigV4A is not public yet, so I guess it's not possible to do an example using SigV4A right now. However,  it's hard to even find a SigV4 go example online so it would be nice to have at least some example here I guess?

**Comment by lovaarte** [comment]
Agree, there is also a greater need for SigV4 examples. We are actually thinking to create a separate repo for SigV4 examples (cc @jhart0). However, at this point I think this repo should only have SigV4A examples and not mix those two as that surely will start being confusing for folks.

**Comment by ChocolateAceCream** [comment]
Hi Artem,

Thanks for your reply.

________________________________

**Pull request closed without merging**
